version: 2
updates:
  - package-ecosystem: "npm"
    target-branch: "main"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
